apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikikube
spec:
  selector:
    matchLabels:
      app: wikikube-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: wikikube-pod
    spec:
      serviceAccountName: secret-read
      containers:
      - name: wikikube-pod
        image: kianjay/wikikube:latest
        ports:
        - containerPort: 8000
