name: wikikube Docker Image Build & Push
on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: create-json
        id: create-json
        uses: SECRET_KEY/create-json@1.1.2
        with:
          name: "secrets.json"
          json: ${{ secrets.SECRET_KEY }}, ${{ secrets.EMAIL_HOST_USER }}, ${{ secrets.EMAIL_HOST_PASSWORD }}
      - 
        name: Check out repository
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build & push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kianjay/wikikube:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

        